[package]
name = "daily-focus-app"
version = "0.1.0"
edition = "2024"

[dependencies]
mockall = "0.13"


[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]
